### ISSUE TITLE
Optional dependency clutters installation log

### ISSUE THREAD

**Issue by selbekk** [wix/commons-validator-js#2] opened 2016-05-06 12:08 UTC
We use this in our project, and it works very nicely - but when we run `npm install`, we get a very verbose error message due to a missing optional dependency - `@wix/wnpm-ci`:

```
npm ERR! registry error parsing json
npm WARN optional Skipping failed optional dependency /commons-validator-js/@wix/wnpm-ci:
npm WARN Unexpected token <
npm WARN <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm WARN <html><head>
npm WARN <title>404 Not Found</title>
npm WARN </head><body>
npm WARN <h1>Not Found</h1>
npm WARN <p>The requested URL /nexus/content/groups/npmgroup/@wix/wnpm-ci was not found on this server.</p>
npm WARN <hr>
npm WARN <address>Apache/2.2.15 (Red Hat) Server at nexus.intern.sparebank1.no Port 443</address>
npm WARN </body></html>
npm WARN 
```

I understand that this totally works for your organization - but it would be great if you could solve it some other way - so that the installation log would stay clean.

**Comment by dleshem** [comment] 2016-08-03 18:05
Fixed in https://github.com/wix/commons-validator-js/commit/eebee68bf0870a135a23adf78dad9bb4ae158d83.

**Comment by dleshem** [comment] 2016-08-03 18:11
Oops, just realized that the issue is about the optional dependency being unavailable.

I'm not aware of a way to silently ignore a missing optional dependency... suggestions?

**Comment by dleshem** [comment] 2016-10-15 21:24
Fixed in https://github.com/wix/commons-validator-js/commit/911b6fe0eb27c220fd66c5897b5a14d12258634b

**Closed by dleshem** 2016-10-15 21:24 UTC
